version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanad-app:latest
    container_name: sanad-web
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./db/custom.db
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=zP8X59TjmATELNBJOHGs2Tf7kIy/G4Qfmd4KN++7hXI=
    volumes:
      - ./prisma/db:/app/prisma/db
